Vagrant.configure("2") do |config|

  config.vm.box = 'centos/7'
  config.vm.hostname = 'maquina-docker'
  config.vm.network 'forwarded_port', guest: 80, host: 8081, hostip: '127.0.0.1'
  config.vm.network 'private_network', ip: '10.10.1.5'
  config.vm.provision 'shell', path: 'arquivo-provisao.sh'

end
